remote_theme: jackw01/jackw01.github.io
title: smallXY
hide_first_h1: true
plugins:
  - jekyll-seo-tag
custom_buttons:
  - 1:
    url: https://workbench.grabcad.com/workbench/projects/gcE4_nd5ZVmsx_kgBHyB1wqYj7J80Bo0aavsQ_ukKZb6I6#/space/gccWt96S3aIfpnmZw99CCyJWk9YLHOaTK3aYx5E1uazplE
    text: View and Download on GrabCAD
