remote_theme: jackw01/jackw01.github.io
title: smallXY
hide_first_h1: true
plugins:
  - jekyll-seo-tag
custom_buttons:
  - 1:
    url: https://1drv.ms/f/s!AsRZF_y9JrDUn5YstvfhQN0uAOajxg?e=yrKd5q
    text: Download CAD Files and BOM
